import "./globals.css";
import { Ysabeau } from "next/font/google";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";

const open_sans = Ysabeau({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={open_sans.className}>
          <Navbar />
          {children}
          <Toaster />
        </body>
      </html>
    </>
  );
}
